-- Drip Nation — provisional catalog seed (migrated from prototype ensureDefaults()).
-- Deterministic prices/stock (originals used Math.random). Replace via admin (Phase 4)
-- or a real Phase-2 curation. Idempotent: on-conflict-do-nothing on slug/sku.
-- Money = integer whole rupees.

insert into categories(name,slug,image,description) values ('Retro Jersey','retro-jersey','assets/images/retro jerseys.jpeg','Authentic vintage football jerseys.') on conflict (slug) do nothing;
insert into categories(name,slug,image,description) values ('Accessories','accessories','assets/images/accessories.jpeg','Chains, caps, bags & watches.') on conflict (slug) do nothing;
insert into categories(name,slug,image,description) values ('Jackets','jackets','assets/images/jackets.jpeg','Premium outerwear essentials.') on conflict (slug) do nothing;
insert into categories(name,slug,image,description) values ('Track & Suit','track-and-suit','assets/images/track and suit.jpeg','Athletic performance meets street.') on conflict (slug) do nothing;

insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Vintage Milan ''92',c.id,1500,null,24,array['S','M','L','XL'],'DN-101',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Classic Inter ''98',c.id,1680,null,42,array['S','M','L','XL'],'DN-102',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Retro Brazil ''70',c.id,1860,1460,7,array['S','M','L','XL'],'DN-103',array['assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Heritage Arsenal ''04',c.id,2040,null,60,array['S','M','L','XL'],'DN-104',array['assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Legend Madrid ''02',c.id,2230,null,15,array['S','M','L','XL'],'DN-105',array['assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Golden Barça ''06',c.id,2410,null,33,array['S','M','L','XL'],'DN-106',array['assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Imperial Roma ''01',c.id,2590,null,9,array['S','M','L','XL'],'DN-107',array['assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Thunder Juve ''96',c.id,2770,2370,71,array['S','M','L','XL'],'DN-108',array['assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Eclipse Ajax ''95',c.id,2950,null,50,array['S','M','L','XL'],'DN-109',array['assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Phantom PSG ''99',c.id,3140,null,18,array['S','M','L','XL'],'DN-110',array['assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Dynasty Bayern ''01',c.id,3320,null,38,array['S','M','L','XL'],'DN-111',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Vortex Chelsea ''05',c.id,3500,null,12,array['S','M','L','XL'],'DN-112',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'100% Breathable Polyester','','Active' from categories c where c.slug='retro-jersey' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Shadow Chain',c.id,300,null,24,array['S','M','L','XL'],'DN-113',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Midnight Beanie',c.id,500,null,42,array['S','M','L','XL'],'DN-114',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Carbon Crossbody',c.id,700,300,7,array['S','M','L','XL'],'DN-115',array['assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Phantom Cap',c.id,900,null,60,array['S','M','L','XL'],'DN-116',array['assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Onyx Wristband',c.id,1100,null,15,array['S','M','L','XL'],'DN-117',array['assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Steel Dog Tag',c.id,1300,null,33,array['S','M','L','XL'],'DN-118',array['assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Noir Bucket Hat',c.id,1500,null,9,array['S','M','L','XL'],'DN-119',array['assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Obsidian Ring',c.id,1700,1300,71,array['S','M','L','XL'],'DN-120',array['assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Venom Snapback',c.id,1900,null,50,array['S','M','L','XL'],'DN-121',array['assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Eclipse Durag',c.id,2100,null,18,array['S','M','L','XL'],'DN-122',array['assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Blaze Lanyard',c.id,2300,null,38,array['S','M','L','XL'],'DN-123',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Iron Pendant',c.id,2500,null,12,array['S','M','L','XL'],'DN-124',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'Premium Stainless Steel & Cotton','','Active' from categories c where c.slug='accessories' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Shadow Bomber',c.id,2000,null,24,array['S','M','L','XL'],'DN-125',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Midnight Varsity',c.id,2360,null,42,array['S','M','L','XL'],'DN-126',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Carbon Coach',c.id,2730,2330,7,array['S','M','L','XL'],'DN-127',array['assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Phantom Windbreaker',c.id,3090,null,60,array['S','M','L','XL'],'DN-128',array['assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Onyx Puffer',c.id,3450,null,15,array['S','M','L','XL'],'DN-129',array['assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Steel Harrington',c.id,3820,null,33,array['S','M','L','XL'],'DN-130',array['assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Noir Flight Jacket',c.id,4180,null,9,array['S','M','L','XL'],'DN-131',array['assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Obsidian Denim',c.id,4540,4140,71,array['S','M','L','XL'],'DN-132',array['assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Venom Track Top',c.id,4910,null,50,array['S','M','L','XL'],'DN-133',array['assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Eclipse Anorak',c.id,5270,null,18,array['S','M','L','XL'],'DN-134',array['assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Blaze Leather',c.id,5640,null,38,array['S','M','L','XL'],'DN-135',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Iron Trucker',c.id,6000,null,12,array['S','M','L','XL'],'DN-136',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'Water-Resistant Nylon Blend','','Active' from categories c where c.slug='jackets' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Shadow Tracksuit',c.id,1300,null,24,array['S','M','L','XL'],'DN-137',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Midnight Jogger Set',c.id,1640,null,42,array['S','M','L','XL'],'DN-138',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Carbon Velour',c.id,1970,1570,7,array['S','M','L','XL'],'DN-139',array['assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Phantom Tech Fleece',c.id,2310,null,60,array['S','M','L','XL'],'DN-140',array['assets/images/i5.jpeg','assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Onyx Windpants',c.id,2640,null,15,array['S','M','L','XL'],'DN-141',array['assets/images/accessories.jpeg','assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Steel Slim Track',c.id,2980,null,33,array['S','M','L','XL'],'DN-142',array['assets/images/i6.jpeg','assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Noir Side-Stripe',c.id,3320,null,9,array['S','M','L','XL'],'DN-143',array['assets/images/WhatsApp Image 2026-07-06 at 15.58.23.jpeg','assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Obsidian Zip Set',c.id,3650,3250,71,array['S','M','L','XL'],'DN-144',array['assets/images/second page image.jpeg','assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Venom Track Pants',c.id,3990,null,50,array['S','M','L','XL'],'DN-145',array['assets/images/jackets.jpeg','assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Eclipse Training Kit',c.id,4330,null,18,array['S','M','L','XL'],'DN-146',array['assets/images/track and suit.jpeg','assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Blaze Warm-Up',c.id,4660,null,38,array['S','M','L','XL'],'DN-147',array['assets/images/i3 (1).jpeg','assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;
insert into products(name,category_id,price,sale,stock,sizes,sku,images,material,description,status) select 'Iron Retro Track',c.id,5000,null,12,array['S','M','L','XL'],'DN-148',array['assets/images/i3 (2).jpeg','assets/images/i4.jpeg','assets/images/i5.jpeg','assets/images/accessories.jpeg'],'Luxury Velour & French Terry','','Active' from categories c where c.slug='track-and-suit' on conflict (sku) do nothing;

-- Promotions (from prototype defaults; validated client-side for UX, server-side in Phase 5)
insert into promos(code,type,value,min_order,max_uses,used,expiry,status) values
  ('DRIP20','percentage',20,2000,200,34,'2026-12-31','Active'),
  ('FIRSTDROP','fixed',500,1500,100,89,'2026-09-30','Active'),
  ('FREESHIP','shipping',0,999,0,156,null,'Active')
on conflict (code) do nothing;
